# Answer 1

In [70]:
import numpy as np
a = np.random.rand(10,1)
print(a)
a.mean()


[[0.7210014 ]
 [0.55340035]
 [0.20692695]
 [0.95321415]
 [0.28464379]
 [0.45880376]
 [0.49962723]
 [0.43205048]
 [0.5132182 ]
 [0.53791314]]


0.516079944821884

# Answer 2

In [82]:
a = np.random.rand(20,1)
print(a)
variance = a.var()
print(variance)
standard_dev = a.std()
print(standard_dev)


[[0.43911456]
 [0.45751459]
 [0.75534738]
 [0.69702278]
 [0.40069918]
 [0.28423623]
 [0.07924314]
 [0.43283112]
 [0.42119246]
 [0.91421537]
 [0.44676597]
 [0.21091123]
 [0.16920257]
 [0.5693719 ]
 [0.17287268]
 [0.97769684]
 [0.73225738]
 [0.10338068]
 [0.38573023]
 [0.46995669]]
0.062379209408177504
0.24975830198048973


# Answer 3

In [8]:
A = np.random.rand(10,20)
B = np.random.rand(20,25)

In [10]:
mat_mul=np.matmul(A,B)
print(mat_mul)

[[3.62301041 3.31290381 2.69246284 3.2417621  3.14244603 3.52767447
  4.17752887 2.51361817 3.03502897 3.0426942  3.790146   2.52497658
  3.37759032 2.36288853 3.15365121 2.76159578 3.54731614 3.91664862
  3.84017748 3.20176441 3.38554684 1.93789521 2.56486299 2.99947544
  2.55441612]
 [6.55623693 6.33362379 6.02564404 5.65322631 6.63717594 7.01715558
  6.09840528 5.04169185 5.50692441 5.62279833 5.67161467 5.24421399
  6.19928106 3.7638291  5.67117283 5.22067832 5.55873273 6.85839357
  6.72307556 6.32883171 6.33217431 5.54516831 5.44294585 6.69780676
  4.94811575]
 [5.20384224 4.56048064 4.66674795 4.4333852  4.82087296 5.32388838
  5.64511722 3.95567288 4.13717653 4.15821413 5.631827   3.97488371
  5.01722357 3.33122339 4.56155995 4.44068491 5.55094346 6.29016835
  6.35295895 4.89744222 5.0295332  3.32675714 4.91172529 4.92129128
  4.0007914 ]
 [6.1451384  5.68442905 5.57209463 5.3970891  5.58414679 6.25470156
  6.5226869  4.8634334  5.24844817 5.48150562 6.37920152 4.78034638
  5.33

In [11]:
mat_mul.shape

(10, 25)

In [12]:
sum = mat_mul.sum()
print(sum)

1269.8272695017536


# Answer 4

In [16]:
arr=np.random.rand(10,1)
print(arr)

[[0.09779997]
 [0.44775976]
 [0.48302054]
 [0.15929454]
 [0.1302693 ]
 [0.45455774]
 [0.61311528]
 [0.28499831]
 [0.90937843]
 [0.91873499]]


In [17]:
def function(x):
    return (1 / (1 + np.exp(-x)))

In [21]:
ans= np.apply_along_axis(function, 0, arr)
print(ans)

[[0.52443052]
 [0.61010647]
 [0.61846088]
 [0.53973964]
 [0.53252135]
 [0.61172233]
 [0.64865111]
 [0.5707712 ]
 [0.71287295]
 [0.71478428]]
